# print("Hello", str(input("Type your name:")), ",COMP1753 module leader")
name= input("Type your name: ")
print(f"Hello {name}, COMP1753 module leader")
print("Hello", name, "COMP1753 module leader")
print("Hello "+ name+ ", COMP1753 module leader")